kind: Deployment
apiVersion: apps/v1
metadata:
  name: stakater-spring-boot
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/stakater-spring-boot
  uid: 1d26607f-2d20-421a-bcd0-1b6599b6aa08
  resourceVersion: '1871'
  generation: 3
  creationTimestamp: '2021-06-14T20:08:11Z'
  labels:
    k8s-app: stakater-spring-boot
  annotations:
    deployment.kubernetes.io/revision: '3'
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      time: '2021-06-14T20:08:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:k8s-app: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector:
            f:matchLabels:
              .: {}
              f:k8s-app: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:k8s-app: {}
              f:name: {}
            f:spec:
              f:containers:
                k:{"name":"stakater-spring-boot"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:privileged: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-06-14T20:16:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: stakater-spring-boot
  template:
    metadata:
      name: stakater-spring-boot
      creationTimestamp: null
      labels:
        k8s-app: stakater-spring-boot
    spec:
      containers:
        - name: stakater-spring-boot
          image: luisjavierjn/stakater-spring-boot:1.0
          env:
            - name: NAME
              value: Stakater
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 3
  updatedReplicas: 3
  readyReplicas: 3
  availableReplicas: 3
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-06-14T20:08:21Z'
      lastTransitionTime: '2021-06-14T20:08:21Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-06-14T20:16:25Z'
      lastTransitionTime: '2021-06-14T20:08:11Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "stakater-spring-boot-7f5b469f99" has successfully
        progressed.
